language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=app -m pytest && coverage report

after_succes:
- coveralls

deploy:
  provider: heroku
  api_key:
    secure: "fast-food-fast-/api/v1"