language: python
python:
  - "3.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - source app/.travis.sh
  - psql -c "create database foodfast;" -U postgres
  - psql -c "create user kinara with password 'kinara';" -U postgres
script:

  - coverage run --source app -m pytest
   # coverage reports

  - python -m coverage report -m

after_success:
  - coveralls
  

